SOURCES = \
	types.ml \
	shuffle.ml \
	parser.mly \
	lexer.mll \
	repr.mli \
	repr.ml \
	unificator.mli \
	unificator.ml \
	evaluator.mli \
	evaluator.ml \
	opl.ml
RESULT = ../bin/opl
ANNOTATE = true
-include OCamlMakefile
