SOURCES = \
	types.ml \
	shuffle.ml \
	parser.mly \
	lexer.mll \
	repr.mli \
	repr.ml \
	unification.mli \
	unification.ml \
	limit.ml \
	var.mli \
	var.ml \
	interpreter.mli \
	interpreter.ml \
	opl.ml
RESULT = ../bin/opl
ANNOTATE = true
-include OCamlMakefile
